name: Build and deploy Node.js app to Azure Web App - Kids-ecom

on:
  push:
    branches:
      - main  # or E-com-major if you want that branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install frontend dependencies (Node.js frontend app)
      - name: Install frontend dependencies
        run: npm install
        working-directory: client

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm install
        working-directory: server

      # If backend serves frontend static files, copy them
      - name: Copy frontend to backend (if needed)
        run: |
          rm -rf server/public
          mkdir -p server/public
          cp -r client/* server/public/

      # Upload backend as artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Kids-ecom'
          slot-name: 'Production'
          package: .
