name: Build and deploy Node.js app to Azure Web App - Kids-ecom

on:
  push:
    branches:
      - main  # Change if you want E-com-major
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install and build frontend
      - name: Install frontend dependencies
        run: npm install
        working-directory: client

      - name: Build frontend
        run: npm run build
        working-directory: client

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm install
        working-directory: server

      # Move frontend build into backend public folder
      - name: Move frontend build to backend
        run: |
          rm -rf server/public
          mv client/build server/public

      # Upload artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Kids-ecom'
          slot-name: 'Production'
          package: .
