name: Deploy to Azure

on:
  push:
    branches:
      - E-com-major

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Azure Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: Kids-ecom
          publish-profile: ${{ secrets.TES2 }}
          package: .
      - name: Test connection to Azure App
        run: curl -I https://Kids-ecom.azurewebsites.net