name: Build and deploy Node.js app to Azure Web App - kid

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Install server dependencies
      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      # Prepare deployment package
      - name: Prepare deployment
        run: |
          # Copy server package.json to root for Azure
          cp ./server/package.json ./package.json
          cp ./server/package-lock.json ./package-lock.json 2>/dev/null || true
          
          # Ensure start script points to server/app.js
          if grep -q '"start": "node app.js"' package.json; then
            sed -i 's#"start": "node app.js"#"start": "node server/app.js"#' package.json
          fi

      # Create zip package with only necessary files
      - name: Zip artifact
        run: |
          # Create a zip with server files and the modified package.json
          zip -r release.zip ./server package.json package-lock.json 2>/dev/null || zip -r release.zip ./server package.json

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: kid
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: release.zip