name: Build and deploy Node.js app to Azure Web App - kid

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # Install and build client
      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Build client project
        working-directory: ./client
        run: npm run build --if-present

      # Install server dependencies
      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      # Prepare deployment package
      - name: Prepare deployment
        run: |
          # Copy server package.json to root for Azure
          cp ./server/package.json ./package.json
          cp ./server/package-lock.json ./package-lock.json || true

          # Ensure start script points to server/app.js
          sed -i 's#"start": "node app.js"#"start": "node server/app.js"#' package.json

          # Copy React build into server/public
          rm -rf ./server/public
          mkdir -p ./server/public
          cp -r ./client/build/* ./server/public/

      # Package only the server + root package.json
      - name: Zip artifact
        run: zip -r release.zip ./server package.json package-lock.json

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: kid
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: release.zip
