name: Deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Create deployment structure
        run: |
          # Create deployment directory
          mkdir -p deployment
          
          # Copy server files (excluding node_modules)
          cp -r server/* deployment/
          rm -rf deployment/node_modules 2>/dev/null || true
          
          # Copy client views and public assets
          mkdir -p deployment/client
          cp -r client/views deployment/client/
          cp -r client/public deployment/client/ 2>/dev/null || mkdir -p deployment/client/public
          
          # Create package.json with correct start command
          echo '{
            "name": "kids-accessories-app",
            "version": "1.0.0",
            "main": "app.js",
            "scripts": {
              "start": "node app.js"
            },
            "dependencies": {}
          }' > deployment/package.json
          
          # Copy dependencies from server package.json
          node -e "
          const fs = require('fs');
          const serverPkg = JSON.parse(fs.readFileSync('server/package.json'));
          const deployPkg = JSON.parse(fs.readFileSync('deployment/package.json'));
          deployPkg.dependencies = serverPkg.dependencies;
          fs.writeFileSync('deployment/package.json', JSON.stringify(deployPkg, null, 2));
          "

      - name: Zip deployment package
        run: |
          cd deployment
          zip -r ../release.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: kid
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: release.zip