name: Build and deploy Node.js app to Azure Web App - kid-com

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3️⃣ Build client
      - name: Install and build client
        working-directory: ./client
        run: |
          npm install
          npm run build

      # 4️⃣ Prepare server folder with client build
      - name: Install server dependencies & copy client build
        working-directory: ./server
        run: |
          npm install
          mkdir -p public
          cp -r ../client/build/* public/

      # 5️⃣ Zip server for deployment
      - name: Archive production build
        run: |
          cd server
          zip -r ../node-app.zip .

      # 6️⃣ Upload artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 7️⃣ Download artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # 8️⃣ Deploy to Azure
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kid-com' # Your Azure Web App name
          slot-name: 'Production'
          package: ./node-app.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
