name: Build and deploy Node.js app to Azure Web App - kid-com

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3️⃣ Install client dependencies
      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      # 4️⃣ Install server dependencies
      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      # 5️⃣ Copy client files to server/public (optional if server serves them)
      - name: Copy client files to server/public
        run: |
          mkdir -p server/public
          cp -r client/* server/public/

      # 6️⃣ Zip server folder for deployment
      - name: Archive production files
        run: |
          cd server
          zip -r ../node-app.zip .

      # 7️⃣ Upload artifact for deploy
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 8️⃣ Download artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # 9️⃣ Deploy to Azure
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kid-com' # Azure Web App name
          slot-name: 'Production'
          package: ./node-app.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
